// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'duration': string;
  'hasUpdates': string;
  'header': string;
  'message': string;
  'pulseShadow': string;
  'root': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
