// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message': string;
  'messages': string;
  'prompt': string;
  'promptButtons': string;
  'promptButtonsPlaceholder': string;
  'promptInput': string;
  'root': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
