// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createNodeButton': string;
  'inner': string;
  'isDragging': string;
  'item': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
