// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'field': string;
  'footer': string;
  'form': string;
  'opened': string;
  'root': string;
  'selectTrigger': string;
}
export const cssExports: CssExports;
export default cssExports;
