// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearButton': string;
  'hint': string;
  'inner': string;
  'input': string;
  'item': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
