// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'changed': string;
  'data': string;
  'editButton': string;
  'editor': string;
  'header': string;
  'isDragging': string;
  'name': string;
  'outputButton': string;
  'preview': string;
  'pulseShadow': string;
  'repeat': string;
  'root': string;
  'type': string;
  'type-function': string;
  'type-table': string;
  'type-text': string;
  'type-view': string;
}
export const cssExports: CssExports;
export default cssExports;
